# Should the Plugin check if the server is in sign-creation reachable?
server-alive: true
# Sign refresh delay, in milliseconds
sign-refresh: 1000
# Ping-TimeOut
timeout: 4000
# Chunk Radius - 0|1|2
chunk-radius: 0
# Max failed connections
server-max-failed-connections: 5
# Enter-Message:
enter-msg: &3You enter Server %server !
# debug mode
debug: false