name: BungeeServerSigns
version: 2.0
main: me.Bentipa.BungeeSignsFree.Core
author: Bentipa
commands:


   bsinfo:
      description: Informations.
      usage: /<command>
      permission: BungeeSigns.info

   createBSSign:
     description: Create a Connection-Sign.
     usage: /<command>
     permission: BungeeSigns.create
     
   removeBSSign:
     description: Remove a Connection-Sign.
     usage: /<command>
     permission: BungeeSigns.remove
      
   bsreload:
     description: Reloads the config.
     usage: /<command>
     permission: BungeeSigns.reload    